name: Metrics

on:
  schedule:
    - cron: "17 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: metrics
  cancel-in-progress: true

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Header
        uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: okanakyol
          template: classic
          base: header
          config_timezone: Europe/Istanbul

      - name: Repositories
        uses: lowlighter/metrics@latest
        with:
          filename: repositories.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: okanakyol
          template: classic
          base: repositories
          config_timezone: Europe/Istanbul

      - name: Activity and community
        uses: lowlighter/metrics@latest
        with:
          filename: activity-community.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: okanakyol
          template: classic
          base: activity, community
          config_timezone: Europe/Istanbul

      - name: Isometric calendar
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: okanakyol
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Follow-up and languages
        uses: lowlighter/metrics@latest
        with:
          filename: followup-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: okanakyol
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          plugin_followup: yes
          plugin_languages: yes
